baseurl:
url: https://666liuchang.github.io
title: 畅畅哥哥
subtitle: "黎明降至，抬头尽是朝阳。"
description: "Chang's personal page"
date_format: "ordinal"

encoding: "utf-8"
side_bar_repo_limit: 5

author: 666liuchang
organization:TYUST
organization_url:https://www.tyust.edu.cn/
github_username: 666liuchang
location:  Taiyuan,China
email: 1165517598@qq.com

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Blogs

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links

# RSS
subscribe_rss: /feed.xml

# Jekyll
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: 666liuchang\666liuchang.github.io

# Search
simple_jekyll_search:
    fulltext: false # full text search enable
    limit: 10 # limitation of the search results to show

# Analytics
google:
    analytics_id: UA-80669434-1
github: [metadata]
